### ISSUE TITLE
Research the rule of EVM padding code

### ISSUE THREAD

**Issue by bdmason** [litentry/evm-processor#102]
Migrated from https://github.com/litentry/litentry-graph/issues/257

**Comment by bdmason** [comment]
@wangminqi this is the method we use to decode `ethers.utils.defaultAbiCoder.decode` https://docs.ethers.io/v5/api/utils/abi/coder/#AbiCoder-decode

**Comment by wangminqi** [comment]
@bianyunjian @lbj2016 This one should concern us too.

**Comment by bdmason** [comment]
Another weird transaction: https://etherscan.io/tx/0x99ab1f82e48155c38e67545115f661461258bbbcb2b91135ec0d955d102dc359

The token addresses in the swap are prefixed with `ff`, if you swap `ff` for `00` then it decodes fine.

**Comment by bdmason** [comment]
The current conclusion is that there is no rule, people sometimes just left pad EVM addresses with garbage. It's easy to handle, take the last 20 characters of the 32 byte hex.

If we want to continue using Ethers to decode transactions we need to submit a PR. I've tried and tested a fix locally, but am currently unaware of the wider impact on the library. Also the library is in the early stage of a major v6 refactor which is currently undocumented. I'll approach them with a PR for a fix there, as the relevant code is now packaged away, which would allow us to pull that in for decoding, and stay on the stable v5 for everything else.

I'm closing as there's no longer anything to research.

**Comment by bdmason** [comment]
Fixed here: https://github.com/litentry/evm-processor/pull/164
