### ISSUE TITLE
Index NFT transfer prices on Opensea

### ISSUE THREAD

**Issue by bdmason** [litentry/evm-processor#126]
### Contract info:

Opensea uses the following contracts to handle transferring assets:

- Wyvern v1: https://etherscan.io/address/0x7be8076f4ea4a4ad08075c2508e481d6c946d12b
- Wyvern v2: https://etherscan.io/address/0x7f268357a8c2552623316e2562d90e642bb538e5

The relevant event we are looking for is:

```
OrdersMatched (bytes32 buyHash, bytes32 sellHash, index_topic_1 address maker, index_topic_2 address taker, uint256 price, index_topic_3 bytes32 metadata)
```

Signature & hash:
```
OrdersMatched(bytes32,bytes32,address,address,uint256,bytes32)
0xc4109843e0b7d514e4c093114b863f8e7d8d9a458c372cd51bfe526b588006c9
```

_This event is the same on both versions of Wyvern_

### Indexer logic:

1. Get logs where `address` matches v1 or v2 & `topic0` is `0xc4109843e0b7d514e4c093114b863f8e7d8d9a458c372cd51bfe526b588006c9` _(check the `OrdersMatched` event and transaction is always a 1 to 1 relationship - investigate if proven wrong - the concern is a multicall or proxy is used, it could complicate our price to asset transfer mapping)_
2. For each log in step 1, get all logs by transaction ID (these contain the assets transferred)
3. From the associated logs, filter those not matching ERC721 `Transfer`, ERC1155 `TransferSingle`, or ERC1155 `TransferBatch`. _Add a check on the topics to prevent ERC20 Transfers being interpreted as ERC721_
4. Make sure the to & from addresses match the `OrdersMatched` event _(check if there are any that don't match and investigate)_
5. Get the price from the `OrdersMatched` data field & divide by the total number of matching transfers _(ERC1155 enumerable will need some investigation as to how quantity is handled, each item in quantity may count in the total number of matching transfers, if not the value of the event/transfer will need to be divided by the quantity)_
6. Save the price data

#### Locally with test files & mongo memory server:

Find a user on Opensea with some transfer history, and select a block range for each one that is relatively small, then run the indexer on those blocks. Check all transfers in that block range are in the database, and that the prices match Opensea. _Repeat for more users until confident_

#### On AWS with a full dataset:

Run the indexer then find users on Opensea and query our graph, checking all their transfers exist and have correct prices.

#### Programatic testing options:

We could sign up for the Opensea API and use it to check our data. We could also use a headless browser. The former would be far less painful.

### Useful links:

- [ERC721 sale on Opensea](https://etherscan.io/tx/0x48db4231fb7de49b624f0860fed5f459ca7231ff1f22ef58f00c1cefd6e454ef#eventlog)
- [ERC1155 (transfer single) sale on Opensea](https://etherscan.io/tx/0x0cf37640cf9a098a3af21554e63602e806242a352e07a9754d5d74365ebd84b1#eventlog)
- ERC1155 (transfer batch) sale on Opensea - TODO
- [Contract code](https://github.com/ProjectWyvern/wyvern-ethereum/blob/master/contracts/exchange/ExchangeCore.sol#L750)

**Comment by geastwood** [comment]
Thanks Ben, would it be possible to estimate on complexity and how long you will need to finish this?

**Comment by bdmason** [comment]
@geastwood assuming all my research it generally correct the hard bit is done, it's just a case of writing some code now. It'll be done this week. [this issue](https://github.com/litentry/evm-processor/issues/127) is a lot more awkward than I first thought, and I'd like to resolve it first. It doesn't actually block Opensea work though
