### ISSUE TITLE
Add Monitoring and Visibility to the lambdas processing

### ISSUE THREAD

**Issue by jdomingos** [litentry/evm-processor#17]
We want to introduce some metrics in some strategic places to give us more insights on what's happening on our processing.

We will need to:
- Identify and profile the places in the code that we want to monitor
- Integrate the tools chosen into the project
- Work on aggregating/graphing these metrics 

The idea is to introduce some elements that are vendor agnostic and the first suggestions rely on this:
https://github.com/vegasbrianc/prometheus
https://www.npmjs.com/package/@matsumana/winston-transport-prometheus

**Comment by geastwood** [comment]
There are already progress here?

Can we identity what else have to be done here?
